language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"

install:
  - "pip install coveralls"
  - "pip install pytest-cov"
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -e . --use-mirrors"

script:
  - "python -m compileall -f ."
  - "python setup.py test"
  - "python setup.py develop"
  - "py.test --cov pypinyin tests/"

after_script:
  - "coveralls"

notifications:
  email: false
